### ISSUE TITLE
Game End Issue

### ISSUE THREAD

**Issue by Gryphon8344** [dasilvacontin/ag-drift#45]
When the round ends it does not restart properly, it just freezes up and you have to refresh to enter the next match. This could also just be a connection issue on my end.

**Comment by dasilvacontin** [comment]
@Gryphon8344 has this happened again, Griffon? I made a fix recently that should properly sync your game with the server if you happen to join the game while a race is ending. This may have caused the issue you're experiencing.

I'll close the issue, but if it happens again, please let me know! I appreciate your help. :)
